version: "3"

services:
  app:
    container_name: pruvo
    restart: always
    build: .
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
  app2:
    container_name: pruvo2
    restart: always
    build: .
    environment:
      - PORT=4000
    ports:
      - "4001:4000"
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./reverse_proxy.conf:/etc/nginx/conf.d/default.conf
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - 8080:8080
    links:
      - app
